name: Deploy to Pages

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.7.0

      - name: Install dependencies
        shell: bash
        run: npm install

      - name: Build
        shell: bash
        run: npm run build -- --configuration=production
